### ISSUE TITLE
Machine lattice and magnets

### ISSUE THREAD

**Issue by jgerity** [jgerity/uspas2016_project3#4]
Edits to this section should be in paper_src/lattice_and_magnets.md, discussion belongs here.
### Tasks
- [x] SVG or CAD figure of machine
- [ ] Edge focusing calculations
- [ ] MAD-X (or etc.) lattice file

**Comment by jgerity** [comment]
Kai is also on this task, need to add him after he is made a repo collaborator

**Comment by Ossssip** [comment]
BTW, why don't we adjust the bending magnets strength to keep the electrons on the same orbit with the decrease of their energy? Then we should not have the number-of-turns limit, but the emission spectra would be shifted over time.

**Comment by jgerity** [comment]
That's an idea that hadn't occurred to me!  It's probably not something that could be done turn-by-turn because of the fast rep rate, but for the 1 GeV designs the energy loss per turn is small enough that perhaps our adjustments to the dipole strength could be sensitive on the order of 100 turns (~ μs), and the shift required would be ~3% over this same time...  

Unfortunately, now that I'm considering the specific numerics for the 1 T case, that would give a ramp rate of `0.03 [T] / 1 [μs] = 30000 T/s`, which is **far** too large to be technologically realizable, I think.  For contrast, with the JLEIC design (where ramp rate is also a concern because of multiple cycles of the booster stage) we have been discussing ramp rates of 1 T/s being pretty demanding.  Granted, those are more iron-dominated magnets than what might be used for this compact ring, but I still think it's too many orders of magnitude all the same.

A good source for ramp-rate sensitivity in dipoles can be found in this [SSC design document](https://www.iaea.org/inis/collection/NCLCollectionStore/_Public/26/069/26069901.pdf).
